mkdir database routes utils
echo "" > database/__init__.py
echo "" > database/connection.py
echo "" > routes/__init__.py
echo "" > routes/auth.py
echo "" > routes/acoes.py
echo "" > utils/__init__.py
echo "" > utils/decorators.py
echo "" > app.py